/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_svmtest_test */

#ifndef _Included_com_example_user_svmtest_test
#define _Included_com_example_user_svmtest_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_user_svmtest_test
 * Method:    test
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_user_svmtest_testtry_test
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_example_user_svmtest_test
 * Method:    check
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_user_svmtest_testtry_check
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
