/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_svmtest_MotionDetect */

#ifndef _Included_com_example_user_svmtest_MotionDetect
#define _Included_com_example_user_svmtest_MotionDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_user_svmtest_MotionDetect
 * Method:    featureExtract
 * Signature: ([[D)[F
 */
JNIEXPORT jdoubleArray JNICALL Java_com_example_user_svmtest_MotionDetect_featureExtract
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_example_user_svmtest_MotionDetect
 * Method:    predictMotion
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_user_svmtest_MotionDetect_predictMotion
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
